title: 16 story bits
description: A one person video game studio
logo: logo.svg

google_analytics: UA-174955070-1
theme: jekyll-theme-minimal
baseurl: /
baseurlagain: /
paginate: 5
plugins:
- jekyll-paginate
- jekyll-feed

company:
  name: Juan Lao Tebar
  email: <span class="nowrap highlighted">16storybits`.and.more`{:.antispam}@gmail.com</span>
  url: https://twitter.com/16_story_bits

collections:
  tag:
    output: true
    permalink: tag/:path/

github:
  is_project_page: false
